import { v4 as uuid } from 'uuid';
export default [
  {
    id: uuid(),
    time: '8:00',
    tee: '|',
    player1: 'Bikram Singh (Am)',
    player2: 'Sachin Chauhan (Am)',
    player3: 'Rudrapratap Singh (Am)',
    player4: 'Nikhil Sharma (Am)',
  },
  {
    id: uuid(),
    time: '8:09',
    tee: '|',
    player1: 'Manoviraj Shekhawat (Am)',
    player2: 'Sukhman Singh (A)',
    player3: 'Col Kukretey (Am)',
    player4: 'Col Vivek Sharma (Am)',
  },
  {
    id: uuid(),
    time: '8:18',
    tee: '|',
    player1: 'Aditya Punia(Am)',
    player2: 'Jai Shandilya(Am)',
    player3: 'Sanjay Singh Meel (Am)',
    player4: 'Paramraj Sandhu (A)',
  },
  {
    id: uuid(),
    time: '8:27',
    tee: '|',
    player1: 'Karan Mehta (Am)',
    player2: 'Harshit Gupta (Am)',
    player3: 'Rehaan James (Am)',
    player4: 'Sahil Ratra (Am)',
  },
  {
    id: uuid(),
    time: '8:36',
    tee: '|',
    player1: 'Aryan Bhandari(A)',
    player2: 'Mitravardhan Singh (A)',
    player3: 'Abhyudaya Rawat(A)',
    player4: 'Kushagra Gaur (Am)',
  },
  {
    id: uuid(),
    time: '8:45',
    tee: '|',
    player1: 'Paramvir (Am)',
    player2: 'Anuj Dubey (Am)',
    player3: 'Ankit Mohindra (Am)',
    player4: 'Kritein Gandotra (Am)',
  },
  {
    id: uuid(),
    time: '8:54',
    tee: '|',
    player1: 'Shiraz Monga (Am)',
    player2: 'Vaibhav Kaila (Am)',
    player3: 'Yuvraajbir Singh Sodhi (Am)',
    player4: 'Akash Deep Singh (Am)',
  },
  {
    id: uuid(),
    time: '9:03',
    tee: '|',
    player1: 'Col Ashish Singh (Am)',
    player2: 'Arjun Gulati (Am)',
    player3: 'Siddharth Sagar(A)',
    player4: 'Krish Rolania (A) ',
  },
  {
    id: uuid(),
    time: '9:12',
    tee: '|',
    player1: 'Kamal Bhatia (Am)',
    player2: 'Satyaj K Chopra (Am)',
    player3: 'Vedant Handa (Am)',
    player4: '',
  },
  {
    id: uuid(),
    time: '9:21',
    tee: '|',
    player1: 'Karan Khanduja (Am)',
    player2: 'Sarthak Madaan (Am)',
    player3: 'Sagar Mehta (Am)',
    player4: '',
  },
  {
    id: uuid(),
    time: '9:30',
    tee: '|',
    player1: 'Vaibhav Nair (Am)',
    player2: 'Prabhnoor Singh (A)',
    player3: 'Mudit Rana (Am)',
    player4: '',
  },
  {
    id: uuid(),
    time: '9:39',
    tee: '|',
    player1: 'Divanshu Nayyar (Am)',
    player2: 'Harsh Gangwar (Am)',
    player3: 'Ankush Saroha (Am)',
    player4: 'Dilawar Singh (Am)',
  },
  {
    id: uuid(),
    time: '9:48',
    tee: '|',
    player1: 'Ravjot Kaur (A)',
    player2: 'Muskaan Bhardwaj (Am)',
    player3: 'Shreshtha Shukla (B)',
    player4: 'Kashika Mishra(B)',
  },
  {
    id: uuid(),
    time: '9:57',
    tee: '|',
    player1: 'Aarushi Bhanot (A)',
    player2: 'Mannat Brar (B)',
    player3: 'Zara Aamina Hussain(A)',
    player4: 'Parnika Sharma(C)',
  },
  {
    id: uuid(),
    time: '10:06',
    tee: '|',
    player1: 'Sandeep Kumar (A)',
    player2: 'Tanay Keshwar (A)',
    player3: 'Aayush Pandey (A)',
    player4: 'Madhav Batra (A)',
  },
  {
    id: uuid(),
    time: '10:15',
    tee: '|',
    player1: 'Akshath sharma (A)',
    player2: 'Aarnav Sharma (A)',
    player3: 'Surya Yadav(A)',
    player4: '',
  },
  {
    id: uuid(),
    time: '10:24',
    tee: '|',
    player1: 'Arnav Dhaka(A)',
    player2: 'Rajyeveer Sultania(A)',
    player3: 'Anish Nangia(A)',
    player4: '',
  },
  {
    id: uuid(),
    time: '10:33',
    tee: '|',
    player1: 'Parth Raman Sood(B)',
    player2: 'Himanshu Nagar(A)',
    player3: 'Manav Kakkar (A)',
    player4: 'Vijayant Pundir (A)',
  },
  {
    id: uuid(),
    time: '10:42',
    tee: '|',
    player1: 'Shat Mishra(A)',
    player2: 'Kanishk K  Vaidwan (A)',
    player3: 'Yadvinder Shergill (A)',
    player4: 'Vinamra Anand (A)',
  },
  {
    id: uuid(),
    time: '10:51',
    tee: '|',
    player1: 'Apurv Chordia (B)',
    player2: 'Hiransh Singh(B)',
    player3: 'Rudra Pratap Singh(B)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:00',
    tee: '|',
    player1: 'Ivan Jolly (B)',
    player2: 'Ayaan Dhaka (B)',
    player3: 'Ranveer Mitroo(B)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:9',
    tee: '|',
    player1: 'Pushan Ganguly(B)',
    player2: 'Anshul Bhati (B)',
    player3: 'Dewan Kabir Nath(B)',
    player4: 'Manraj S Deol(B)',
  },
  {
    id: uuid(),
    time: '11:18',
    tee: '|',
    player1: 'Harsh Singh (B) ',
    player2: 'MA Arush(B)',
    player3: 'Ritik Madan(B)',
    player4: 'Zorawar Randhawa(B)',
  },
  {
    id: uuid(),
    time: '11:27',
    tee: '|',
    player1: 'Adwaitya Thapa (C)',
    player2: 'Neil Jolly (C)',
    player3: 'Vihaan Jain(C)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:36',
    tee: '|',
    player1: 'Nirvaan Khandelwal (C)',
    player2: 'Bhavesh Nirwan (C)',
    player3: 'Sohang Kantor(C)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:45',
    tee: '|',
    player1: 'Jivraj Khurana(C)',
    player2: 'Arshvant Srivastava (C) ',
    player3: 'Vedant Sodhi Banerjee(C)',
    player4: 'Shubham Kumar(C)',
  },
  {
    id: uuid(),
    time: '11:54',
    tee: '|',
    player1: 'Aditya Misra (D)',
    player2: 'Shaurea Vardhan (D)',
    player3: 'Chaitanya Pandey (D)',
    player4: 'Arihaan Beri (D)',
  },
  {
    id: uuid(),
    time: '12:03',
    tee: '|',
    player1: 'Medhansh Singh Bisht (D)',
    player2: 'Shiksha Jain (D)',
    player3: 'Aney Shanker (D)',
    player4: 'Naina Kapoor (D)',
  },
  {
    id: uuid(),
    time: '12:12',
    tee: '|',
    player1: 'Amaira Gulati (E)',
    player2: 'Samar Baijal (E)',
    player3: 'Ojaswini Saraswat (E)',
    player4: '',
  },
];
