import { v4 as uuid } from 'uuid';
export default [
  {
    id: uuid(),
    time: '11:00 AM',
    tee: '|',
    player1: 'NIKHIL SHARMA (AM)',
    player2: 'TANISHA KALYAN (AM)',
    player3: 'HEENA KANG (AM)',
    player4: 'MUSKAAN (AM)',
  },
  {
    id: uuid(),
    time: ' 11:09 AM',
    tee: '|',
    player1: 'ALASANA JALLOW (AM)',
    player2: 'ADITYA PUNIA (AM)',
    player3: 'KARAN KHANDUJA (AM)',
    player4: 'Karan Mehto  (AM)',
  },
  {
    id: uuid(),
    time: '11:18 AM',
    tee: '|',
    player1: 'PRAVEEN SENTHIL (A)',
    player2: 'MANRAJ S DEOL (B)',
    player3: 'ANSHUL BHATI (B)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11.27 AM',
    tee: '|',
    player1: ' AARUSHI BHANOT (A)',
    player2: 'MEHAR NIJJER (A)',
    player3: 'SHREYA SABHERWAL (A)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:36 AM',
    tee: '|',
    player1: 'CEERAT KANG (B)',
    player2: 'NITZANA BHATIA (B)',
    player3: 'NIDHI SINGH (A)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:45 AM',
    tee: '|',
    player1: 'KANAV CHAUHAN (B)',
    player2: 'AJAY KUMAR (B)',
    player3: 'PRANAV KHANDELWAL (B)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:54 AM',
    tee: '|',
    player1: 'PARTH RAMAN SOOD (B)',
    player2: 'SHUBHAM KUMAR (B)',
    player3: 'HARSH SINGH (B)',
    player4: '',
  },
  {
    id: uuid(),
    time: '12:03 PM ',
    tee: '|',
    player1: 'ARSHVANT SRIVASTAVA (C)',
    player2: 'BHAVESH NIRWAN (C)',
    player3: 'ANEY SHANKKAR (C)',
    player4: 'SMYAAN GUPTA (C)',
  },
  {
    id: uuid(),
    time: '12:12 PM',
    tee: '|',
    player1: 'Angad Mohan Singh (C)',
    player2: 'Prince Bansal (C)',
    player3: 'MUudit Aggarwal (C)',
    player4: 'Aaliya Baroliya (C)',
  },
  {
    id: uuid(),
    time: '12:21 PM',
    tee: '|',
    player1: 'Nikunj Singhal (C) ',
    player2: 'Jivraj Khurana (C) ',
    player3: 'Zorawar Singh Toor (C) ',
    player4: 'Ishaan Kapur (C) ',
  },
  {
    id: uuid(),
    time: '12:30 PM',
    tee: '|',
    player1: 'Arihaan Beri (D)',
    player2: 'Yajas Mehrotra (D)',
    player3: 'Ravi karan Sekhon (D)',
    player4: '',
  },
  {
    id: uuid(),
    time: '12:39 PM',
    tee: '|',
    player1: 'Guneet Sekhon (D)',
    player2: 'Ashima Chachra (D)',
    player3: 'Naina Kapoor (D)',
    player4: '',
  },
  {
    id: uuid(),
    time: '12:48 PM',
    tee: '|',
    player1: 'Avviraaj Kaila (E)',
    player2: 'Ojaswini Saraswat (E)',
    player3: 'Zorawar Sandhu (E)',
    player4: '',
  },
  {
    id: uuid(),
    time: '12:57 AM',
    tee: '|',
    player1: 'Aaravv kaila (E)',
    player2: 'Shiv Shankar Madal (E)',
    player3: '',
    player4: '',
  }];
