import { v4 as uuid } from 'uuid'
export default [
  {
    id: uuid(),
    time: '8:00 AM',
    tee: '|',
    player1: 'Surya (Am)',
    player2: 'Gurkirpal Singh (Am)',
    player3: 'Divanshu Nayyar (Am)',
    player4: 'Irman Sharma (Am)',
  },
  {
    id: uuid(),
    time: ' 8:09 AM',
    tee: '|',
    player1: 'Nikhil Sharma (Am)',
    player2: 'Jaiveer Singh (Am)',
    player3: 'Ankush Saroha (Am)',
    player4: 'Karan Mehto  (Am)',
  },
  {
    id: uuid(),
    time: '8:18 AM',
    tee: '|',
    player1: 'Aabir Chaudhary (Am) ',
    player2: 'Abhishek (AM)',
    player3: 'Aasim (AM)',
    player4: 'Saurav Das (AM)',
  },
  {
    id: uuid(),
    time: '8:27 AM',
    tee: '|',
    player1: 'Vikas Shukla (Am) ',
    player2: 'Raj Patal (Am) ',
    player3: 'Sonu (Am) ',
    player4: 'Sahil Gupta (Am)',
  },
  {
    id: uuid(),
    time: '8:36 AM',
    tee: '|',
    player1: 'Muskaan Bhardwaj (Am)',
    player2: 'Ira Aggarwal (A)',
    player3: 'Aarti Misra (Am)',
    player4: '',
  },
  {
    id: uuid(),
    time: '8:45 AM',
    tee: '|',
    player1: 'Heena Kang (Am)',
    player2: 'Aarushi Bhanot (A)',
    player3: 'Mehar Nijjer (A)',
    player4: '',
  },
  {
    id: uuid(),
    time: '8:54 AM',
    tee: '|',
    player1: 'Ishita (A)',
    player2: 'Ceerat Kang (B)',
    player3: 'Henaaz Khera (B)',
    player4: 'Mannat Brar (B) ',
  },
  {
    id: uuid(),
    time: '9:03 AM',
    tee: '|',
    player1: 'Abhyudaya Rawat (A)',
    player2: 'Akashhdeep Singh (AM)',
    player3: 'Aryan Bhandari (AM) ',
    player4: '',
  },
  {
    id: uuid(),
    time: '9:12 AM',
    tee: '|',
    player1: 'Gurmanijt Dhillon (A)',
    player2: 'Dilawer Singh (A)',
    player3: 'Mohul Dhingra (A)',
    player4: '',
  },
  {
    id: uuid(),
    time: '9:21 AM',
    tee: '|',
    player1: 'Manjodh Singh (A) ',
    player2: 'Umed Kumar (A) ',
    player3: 'Aditya Sood (A) ',
    player4: 'Ajay Pal Bajwa (A) ',
  },
  {
    id: uuid(),
    time: '9:30 AM',
    tee: '|',
    player1: 'Krish Chawla (B) ',
    player2: 'Ajay Kumar (B)',
    player3: 'Kuldeep Singh Dhesi (B)',
    player4: 'Anupam Dahiya (A)',
  },
  {
    id: uuid(),
    time: '9:39 AM',
    tee: '|',
    player1: 'Ivan Jolly (B)',
    player2: 'Ransher Singh Randhawa (B)',
    player3: 'Iren Singh (B) ',
    player4: 'Parnav Khandelwal (AM)',
  },
  {
    id: uuid(),
    time: '9.48 AM',
    tee: '|',
    player1: 'Guntas Kaur Sandhu (C)',
    player2: 'Prabhleen Kaur (C)',
    player3: 'Jaanvi Singh (C) ',
    player4: 'Ganika Goyal (C) ',
  },
  {
    id: uuid(),
    time: '9:57 AM',
    tee: '|',
    player1: 'Waris Kamboj (C) ',
    player2: 'Adishwar singh Chahal (C)',
    player3: 'Hriday Rialch (C)',
    player4: '',
  },
  {
    id: uuid(),
    time: '10:06 AM',
    tee: '|',
    player1: 'Danish Verma (D) ',
    player2: 'Danish Verma (D) ',
    player3: 'Gurshaans Dhillon (D) ',
    player4: 'Gunnet Sekhon (D) ',
  },
  {
    id: uuid(),
    time: '10:15 AM',
    tee: '|',
    player1: 'Aryaveer Singh Grewal (D) ',
    player2: 'Fatehvir Singh (D) ',
    player3: 'Anhad Kaur (D) ',
    player4: 'Advika Datta (D) ',
  },
  {
    id: uuid(),
    time: '10:25 AM',
    tee: '|',
    player1: 'Ravi Karan Sekhon (E)',
    player2: 'Nihaal Cheema (E)',
    player3: 'Zorawar Sandhu (E)',
    player4: '',
  },
  {
    id: uuid(),
    time: '10:34 AM',
    tee: '|',
    player1: 'Ezra Cavo (E)',
    player2: 'Sohraabs Talwar (E)',
    player3: 'Ojaswini Saraswat (E) ',
    player4: '',
  },
  {
    id: uuid(),
    time: '10:43 AM',
    tee: '|',
    player1: 'Shiv Shankar Mandal (E) ',
    player2: 'Sahib Aujla (E) ',
    player3: 'Zurawar Singh (E) ',
    player4: '',
  },
]
