import { v4 as uuid } from 'uuid';
export default [
  {
    id: uuid(),
    time: '9:00 AM',
    tee: '|',
    player1: 'Aditya Punia (AM)',
    player2: 'Nikhil Sharma (AM)',
    player3: 'Sanjay Singh Meel (AM)',
    player4: 'Paramraj S Sandhu (A)',
  },
  {
    id: uuid(),
    time: ' 9:07 AM',
    tee: '|',
    player1: 'Tushar Narang (AM)',
    player2: 'Ajay Pal SIngh Bajwa (AM)',
    player3: 'Shubham Goyal (AM)',
    player4: 'Gurmanjit S Dhillon (AM)',
  },
  {
    id: uuid(),
    time: '9:15 AM',
    tee: '|',
    player1: 'Mitravardhan SIngh (A) ',
    player2: 'Col Kukretey (AM)',
    player3: 'Gaurav Swami (AM)',
    player4: 'Pramod Kumar (AM)',
  },
  {
    id: uuid(),
    time: '9:22 AM',
    tee: '|',
    player1: 'Aryan bhandari (A) ',
    player2: 'Abhyudaya Rawat (A) ',
    player3: 'Rigveda Poddar (B) ',
    player4: 'Sagar Mehto (AM)',
  },
  {
    id: uuid(),
    time: '9:30 AM',
    tee: '|',
    player1: 'Kunal Chellani (AM)',
    player2: 'Ankush Saroha (AM)',
    player3: 'Apurv Chordia (B) ',
    player4: 'Sachin Chauhan (AM) ',
  },
  {
    id: uuid(),
    time: '9:37 AM',
    tee: '|',
    player1: 'Dilawer Singh (AM)',
    player2: 'Divanshu Nayyar (AM)',
    player3: 'Vedant Handa (AM)',
    player4: 'Parteet s sekhon (A) ',
  },
  {
    id: uuid(),
    time: '9:45 AM',
    tee: '|',
    player1: 'Kush Goyal (AM)',
    player2: 'Mudit Khanna (AM)',
    player3: 'Sarthak Madaan (AM)',
    player4: 'Ajit Kumar (AM) ',
  },
  {
    id: uuid(),
    time: '9:52 AM',
    tee: '|',
    player1: 'Krishna Kumar (AM)',
    player2: 'Karan Mehto (AM)',
    player3: 'Gurkirpal Singh (AM) ',
    player4: 'Yadvinder Shergill (AM) ',
  },
  {
    id: uuid(),
    time: '10:00 AM',
    tee: '|',
    player1: 'Prabhnoor Singh (A)',
    player2: 'Arjun Singh Bhatia (A)',
    player3: 'Aditya Sood (A)',
    player4: 'Samarveer Singh (A) ',
  },
  {
    id: uuid(),
    time: '10:07 AM',
    tee: '|',
    player1: 'Vishavjeet Singh (A) ',
    player2: 'Vasu Sehgal (A) ',
    player3: 'Akashdeep Singh (A) ',
    player4: 'Anish Nangia (A) ',
  },
  {
    id: uuid(),
    time: '10.15 AM',
    tee: '|',
    player1: 'Abhiraaj Singh (A) ',
    player2: 'Hersh Pegwal (A) ',
    player3: 'Mohul Dhingra (A) ',
    player4: 'Ravi Mandal (AM)',
  },
  {
    id: uuid(),
    time: '10:22 AM',
    tee: '|',
    player1: 'Manraj s deol (B) ',
    player2: 'Divijay Singh (B) ',
    player3: 'Ravjot K Dosanjh (A) ',
    player4: 'Aabir Choudhary (AM)',
  },
  {
    id: uuid(),
    time: '10.30 AM',
    tee: '|',
    player1: 'Aarti Misra (AM)',
    player2: 'Henaaz (B) ',
    player3: 'Sakshi Mehta (A) ',
    player4: 'Ceerat Kang (B) ',
  },
  {
    id: uuid(),
    time: '10:37 AM',
    tee: '|',
    player1: 'Jiah kang (B) ',
    player2: 'Heena Kang (A) ',
    player3: 'Mehar Nijjer (A) ',
    player4: 'Mannat Brar (B)',
  },
  {
    id: uuid(),
    time: '10:45 AM',
    tee: '|',
    player1: 'M A Arush (B) ',
    player2: 'Ritik Madan (B) ',
    player3: 'Bhavya mann (B) ',
    player4: 'Devin Singh (B) ',
  },
  {
    id: uuid(),
    time: '10:52 AM',
    tee: '|',
    player1: 'Jai Gupta (B) ',
    player2: 'Arnav Dhaka (B) ',
    player3: 'Samarpratap Singh Sandhu (B) ',
    player4: 'Ivan Jolly (B) ',
  },
  {
    id: uuid(),
    time: '10:59 AM',
    tee: '|',
    player1: 'Ransher SIngh Randhawa (B)',
    player2: 'Waris KAMboj (B)',
    player3: 'Arindam Sudan (B)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:07 AM',
    tee: '|',
    player1: 'M A Arush (B)',
    player2: 'Ayaan Dhaka (B)',
    player3: 'Krish chawla (B) ',
    player4: 'Vijayant Pundir (A)',
  },
  {
    id: uuid(),
    time: '11:14 AM',
    tee: '|',
    player1: 'Manyaveer Bhadoo (B) ',
    player2: 'Sidak singh talwar (C ) ',
    player3: 'Neev Gujrati (C ) ',
    player4: 'Rannvijay S Gill (C ) ',
  },
  {
    id: uuid(),
    time: '11:22 AM',
    tee: '|',
    player1: 'Gurbanie S Star ( C) ',
    player2: 'Anahita Pusri (C )  ',
    player3: 'Rabab Kahlon (D) ',
    player4: 'Ganika goel (D) ',
  },
  {
    id: uuid(),
    time: '11:29 AM',
    tee: '|',
    player1: 'Guneet Sekhon (D) ',
    player2: 'Arjunveer shishir (D)',
    player3: 'Danish Verma (D) ',
    player4: 'Hriday Rialch (D) ',
  },
  {
    id: uuid(),
    time: '11:37 AM',
    tee: '|',
    player1: 'Shaurya Dagar (D) ',
    player2: 'Daiwik Jain (D) ',
    player3: 'Samriddh C Thakur (D)  ',
    player4: 'Ravikaran Singh Sekhon (D) ',
  },
  {
    id: uuid(),
    time: '11:44 AM',
    tee: '|',
    player1: 'Ojaswini saraswat (E )  ',
    player2: 'Ezra Cavo (E)  ',
    player3: 'Naina Kapoor (E) ',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:52 AM',
    tee: '|',
    player1: 'Sohraab singh talwar (E ) ',
    player2: 'SAMar Baijal (E ) ',
    player3: 'Anay Aggarwal (E ) ',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:59 AM',
    tee: '|',
    player1: 'nihaal cheema (E ) ',
    player2: 'Fatehvir singh (E )  ',
    player3: 'Shiv Shankar Mandal (E ) ',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:45',
    tee: '|',
    player1: 'Jivraj Khurana(C)',
    player2: 'Arshvant Srivastava (C) ',
    player3: 'Vedant Sodhi Banerjee(C)',
    player4: 'Shubham Kumar(C)',
  },
  {
    id: uuid(),
    time: '11:54',
    tee: '|',
    player1: 'Aditya Misra (D)',
    player2: 'Shaurea Vardhan (D)',
    player3: 'Chaitanya Pandey (D)',
    player4: 'Arihaan Beri (D)',
  },
  {
    id: uuid(),
    time: '12:03',
    tee: '|',
    player1: 'Medhansh Singh Bisht (D)',
    player2: 'Shiksha Jain (D)',
    player3: 'Aney Shanker (D)',
    player4: 'Naina Kapoor (D)',
  },
  {
    id: uuid(),
    time: '12:12',
    tee: '|',
    player1: 'Amaira Gulati (E)',
    player2: 'Samar Baijal (E)',
    player3: 'Ojaswini Saraswat (E)',
    player4: '',
  },
];
